/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientservergui;

import java.awt.event.KeyEvent;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.plaf.basic.BasicTextFieldUI;

/**
 *
 * @author Gabby
 */
public class ClientGuii extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
    private boolean connected;
    private Client client;
    private int defaultPort;
    private String defaultHost;
    private boolean isLogedIn = false;
    int xMouse;
    int yMouse;

    ClientGuii(String host, int port) {
        super("Chat Client");
        initComponents();
        defaultPort = port;
        defaultHost = host;
        tfServer.setText(host);
        tfPort.setText("" + port);
        tf.setText("Enter username");
        ta.setText("Welcome to the chat room\n");
        tfServer.setUI(new BasicTextFieldUI());
        tfPort.setUI(new BasicTextFieldUI());
        ta.setEnabled(false);
        tf.setEnabled(false);
        send.setEnabled(false);
        whoIsIn.setEnabled(false);
        logout.setEnabled(false);
    }

    void append(String str) {
        ta.append(str);
        ta.setCaretPosition(ta.getText().length() - 1);
    }

    void connectionFailed() {
        login.setEnabled(true);
        logout.setEnabled(false);
        whoIsIn.setEnabled(false);
        label.setText("Enter your username below");
        tf.setText("Anonymous");
        tfPort.setText("" + defaultPort);
        tfServer.setText(defaultHost);
        tfServer.setEditable(false);
        tfPort.setEditable(false);
        connected = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        tf = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        login = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        tfServer = new javax.swing.JTextField();
        tfPort = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        whoIsIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(34, 35, 53));
        jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel15MouseDragged(evt);
            }
        });
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 410));

        jPanel14.setBackground(new java.awt.Color(243, 240, 247));
        jPanel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel15MouseDragged(evt);
            }
        });
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel15MousePressed(evt);
            }
        });
        jPanel14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(41, 152, 162));
        jPanel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel15MouseDragged(evt);
            }
        });
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel15MousePressed(evt);
            }
        });

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Socket Programming");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel15MousePressed(evt);
            }
        });
        label1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel15MouseDragged(evt);
            }
        });
        label1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("Socket Programming");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel15MousePressed(evt);
            }
        });
        label2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel15MouseDragged(evt);
            }
        });
        label2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });
        jPanel14.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 0, 500, -1));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 650, 20));

        ta.setColumns(20);
        ta.setRows(5);
        ta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(ta);

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, 470, 320));

        tf.setText("Enter your message here");
        tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });
        jPanel13.add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 390, 40));

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        send.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taKeyPressed(evt);
            }
        });
        jPanel13.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 70, 40));

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel13.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 70, 40));

        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel13.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 70, 40));

        tfServer.setText("127.0.0.1");
        tfServer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfServerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfServerKeyReleased(evt);
            }
        });
        jPanel13.add(tfServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 98, 150, 30));

        tfPort.setText("8888");
        tfPort.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfPort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfServerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfServerKeyReleased(evt);
            }
        });
        jPanel13.add(tfPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 148, 150, 30));

        tfName.setText("Anonymous");
        tfName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfServerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfServerKeyReleased(evt);
            }
        });
        jPanel13.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 48, 150, 30));

        label.setText("Port");
        jPanel13.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        label4.setText("Enter Username");
        jPanel13.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        label5.setText("Server");
        jPanel13.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        whoIsIn.setText("Whois");
        whoIsIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whoIsInActionPerformed(evt);
            }
        });
        jPanel13.add(whoIsIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 183, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientservergui/back.png"))); // NOI18N
        jLabel1.setText(" ");
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 150, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String username = tfName.getText().trim();
        if (username.length() == 0) {
            return;
        }
        String server = tfServer.getText().trim();
        if (server.length() == 0) {
            return;
        }
        String portNumber = tfPort.getText().trim();
        if (portNumber.length() == 0) {
            return;
        }
        int port = 0;
        try {
            port = Integer.parseInt(portNumber);
        } catch (Exception en) {
            return;
        }
        client = new Client(server, port, username, this);
        if (!client.start()) {
            return;
        }
        tf.setText("");
        label.setText("Username");
        connected = true;
        login.setEnabled(false);
        logout.setEnabled(true);
        whoIsIn.setEnabled(true);
        ta.setEnabled(true);
        tf.setEnabled(true);
        tfServer.setEditable(false);
        tfPort.setEditable(false);
        isLogedIn = true;
        send.setEnabled(true);


    }//GEN-LAST:event_loginActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        client.sendMessage(new ChatMessage(ChatMessage.LOGOUT, ""));
        send.setEnabled(false);
        whoIsIn.setEnabled(false);
        tf.setEnabled(false);

    }//GEN-LAST:event_logoutActionPerformed

    private void whoIsInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whoIsInActionPerformed
        client.sendMessage(new ChatMessage(ChatMessage.WHOISIN, ""));

    }//GEN-LAST:event_whoIsInActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, tf.getText()));
        tf.setText("");
    }//GEN-LAST:event_sendActionPerformed

    private void jPanel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel15MouseDragged

    private void jPanel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MousePressed
        xMouse = evt.getX();

        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel15MousePressed

    private void taKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (isLogedIn = true) {
                client.sendMessage(new ChatMessage(ChatMessage.MESSAGE, tf.getText()));
                tf.setText("");
            }

        }
    }//GEN-LAST:event_taKeyPressed

    private void tfServerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfServerKeyReleased

    }//GEN-LAST:event_tfServerKeyReleased

    private void tfServerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfServerKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (isLogedIn = false) {
                String username = tfName.getText().trim();
                if (username.length() == 0) {
                    return;
                }
                String server = tfServer.getText().trim();
                if (server.length() == 0) {
                    return;
                }
                String portNumber = tfPort.getText().trim();
                if (portNumber.length() == 0) {
                    return;
                }
                int port = 0;
                try {
                    port = Integer.parseInt(portNumber);
                } catch (Exception en) {
                    return;
                }
                client = new Client(server, port, username, this);
                if (!client.start()) {
                    return;
                }
                tf.setText("");
                label.setText("Username");
                connected = true;
                login.setEnabled(false);
                logout.setEnabled(true);
                whoIsIn.setEnabled(true);
                ta.setEnabled(true);
                tf.setEnabled(true);
                tfServer.setEditable(false);
                tfPort.setEditable(false);
                send.setEnabled(true);
                isLogedIn = true;
            }
        }
    }//GEN-LAST:event_tfServerKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGuii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGuii("localhost", 1500).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JButton send;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPort;
    private javax.swing.JTextField tfServer;
    private javax.swing.JButton whoIsIn;
    // End of variables declaration//GEN-END:variables
}
